// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGagAQBX3qlGYb-Swihw2GDr4UDWRMWIw',
    appId: '1:627637393500:android:b53dc1039cebbea2e56e99',
    messagingSenderId: '627637393500',
    projectId: 'cleancode-d19d6',
    storageBucket: 'cleancode-d19d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnqE3YVCw0e79JsPHrQe2dJAMmPp_OJmA',
    appId: '1:627637393500:ios:b845d5e611451db6e56e99',
    messagingSenderId: '627637393500',
    projectId: 'cleancode-d19d6',
    storageBucket: 'cleancode-d19d6.firebasestorage.app',
    iosBundleId: 'com.example.cleanArchitectureWeatherNewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPY68JNIG4dOdvIr8hqZdCufsYCQfxd8s',
    appId: '1:627637393500:web:b64d159f38beb182e56e99',
    messagingSenderId: '627637393500',
    projectId: 'cleancode-d19d6',
    authDomain: 'cleancode-d19d6.firebaseapp.com',
    storageBucket: 'cleancode-d19d6.firebasestorage.app',
    measurementId: 'G-QGYLLTCHMW',
  );
}
